[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling", "hatch-vcs" ]

[project]
name = "tap-smoke-test"
dynamic = [ "version" ]
description = "Singer tap for SmokeTest, built with the Meltano SDK for Singer Taps"
license = "Apache-2.0"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dependencies = [
  "genson~=1.4",
  "requests~=2.34",
  "singer-sdk~=0.54.5",
  "typing-extensions>=4.13.2; python_full_version<'3.12'",
]
[[project.maintainers]]
name = "Meltano team and contributors"
email = "hello@meltano.com"
[[project.authors]]
name = "Meltano team and contributors"
email = "hello@meltano.com"
[project.scripts]
tap-smoke-test = "tap_smoke_test.tap:TapSmokeTest.cli"

[dependency-groups]
dev = [
  { include-group = "testing" },
  { include-group = "typing" },
]
testing = [
  "pytest~=9.1",
  "singer-sdk[testing]",
]
typing = [
  "mypy>=2.3.1",
  "ty>=0.0.79",
]

[tool.hatch.version]
fallback-version = "0.0.0.dev0"
source = "vcs"

[tool.ruff]
line-length = 120
[tool.ruff.lint]
select = [
  "A",
  "ANN",
  "ARG",
  "B",
  "BLE",
  "C4",
  "C9",
  "D",
  "DTZ",
  "FA",
  "FBT",
  "FURB",
  "G",
  "I",
  "ICN",
  "LOG",
  "N",
  "PERF",
  "PTH",
  "RUF",
  "SIM",
  "T10",
  "TC",
  "TID",
  "UP",
]
per-file-ignores."tests/*" = [
  "ANN",
  "D1",
]
flake8-annotations.allow-star-arg-any = true
flake8-annotations.mypy-init-return = true
flake8-annotations.suppress-dummy-args = true
isort.required-imports = [
  "from __future__ import annotations",
]
pydocstyle.convention = "google"

[tool.pyproject-fmt]
table_format = "long"

[tool.mypy]
overrides = [ { module = [
    "genson.*",
  ], ignore_missing_imports = true } ]
